---
vpn_sysctl_tuning_enabled: true
vpn_sysctl_settings:
  net.core.default_qdisc: fq
  net.ipv4.tcp_congestion_control: bbr
  net.netfilter.nf_conntrack_max: "65536"
vpn_apply_qdisc_to_default_route: true
