---
network_tuning_sysctl_tuning_enabled: true
network_tuning_sysctl_settings:
  net.core.default_qdisc: fq
  net.ipv4.tcp_congestion_control: bbr
  net.netfilter.nf_conntrack_max: "65536"
network_tuning_apply_qdisc_to_default_route: true
