---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - fail2ban
      - gnupg
      - logrotate
      - openssh-server
      - python3-apt
      - ufw
    update_cache: true
    cache_valid_time: 3600
    state: present
