---
log_retention_enabled: true
log_retention_journald_system_max_use: 200M
log_retention_journald_system_keep_free: 1G
log_retention_journald_system_max_file_size: 50M
log_retention_journald_runtime_max_use: 50M
log_retention_btmp_logrotate_enabled: true
log_retention_btmp_logrotate_size: 25M
log_retention_btmp_logrotate_rotate: 1
